services:
  - type: web
    name: sendgrid-python-poc
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: OPENAI_KEY
        sync: false
      - key: SENDGRID_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
